<?php

/**
 * @file
 * This module adds Google Maps support for the contact page
 */

/**
 * Implements hook_menu
 */
function pharma_contact_menu() {
  $items['admin/config/pharma/contact'] = array(
    'title' => t('Contact Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pharma_contact_admin_form'),
    'file' => 'pharma_contact.admin.inc',
    'access arguments' => array('administer pharma contact settings'),
  );
  
  return $items;
}


/**
 * Implements hook_permission
 */
function pharma_contact_permission() {
  return array(
    'administer pharma contact settings' => array(
      'title' => t('Administer contact settings'),
      'description' => t('Administer the contact settings for this Pharma site.'),
    ),
  );
}